name: Build & Deploy

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [data_updated]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - uses: appleboy/scp-action@master
        with:
          source: public/*
          target: /var/www/galactech/html
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/galactech/html/
            mv ./public/* ./
